#!/bin/sh
color="\033[38;5;";nb=0;nb2=1
echo "\n=================== colors very hard tab by dnetto ==================="
while [ $nb -lt 255 ] ; do printf "$color${nb}m| %3d |\033[0m" ${nb} ; if [ $nb2 -eq 10 ] ; then nb2=0 ; echo ""; fi ; nb=`expr $nb + 1`; nb2=`expr $nb2 + 1` ; done
echo "\n=================== colors very hard tab by dnetto ===================\n"